// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace HarmonyExtension
{
    internal sealed partial class Vsix
    {
        public const string Id = "HarmonyExtension";
        public const string Name = "HarmonyExtension";
        public const string Description = @"Adds convenient ways to copy targets for Andreas Pardeike's Harmony.";
        public const string Language = "en-US";
        public const string Version = "1.0.0";
        public const string Author = "Company";
        public const string Tags = "";
    }
}
