// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace HarmonyExtension
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string HarmonyExtensionString = "802359e0-57a5-4a96-b5c1-5b4a4532c99a";
        public static Guid HarmonyExtension = new Guid(HarmonyExtensionString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int HarmonyMainMenu = 0x0001;
        public const int HarmonyContextMenu = 0x0002;
        public const int HarmonyMenuGroup = 0x0010;
        public const int AnnotatedPrefixCommand = 0x0100;
        public const int AnnotatedPostfixCommand = 0x0101;
        public const int ManualPrefixCommand = 0x0110;
        public const int ManualPostfixCommand = 0x0111;
    }
}